ballball.lo: /home/www/no9adm/daemon/ballball/ballball.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/www/no9adm/daemon/ballball $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/www/no9adm/daemon/ballball/ballball.c -o ballball.lo 
$(phplibdir)/ballball.la: ./ballball.la
	$(LIBTOOL) --mode=install cp ./ballball.la $(phplibdir)

./ballball.la: $(shared_objects_ballball) $(BALLBALL_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_ballball) $(BALLBALL_SHARED_LIBADD)

